import { X_DISC2_HREF } from "@/lib/site";

export const theyDidntShipDisc2 = {
  slug: "they-didnt-ship-disc-2",
  title: "They Didn't Ship Disc 2",
  kicker: "Essay · 4 September 2026",
  date: "2026-09-04",
  dateLabel: "4 September 2026",
  byline: "Jonathan",
  dek: "Square put the finale on one disc. The rest is a download.",
  standfirst:
    "Why one disc versus two — and why the middle is worse than picking a side.",
  xHref: X_DISC2_HREF,
  pullQuote: "A day-one download is ugly for collectors. It's also a lock.",
  pullAfter:
    "A day-one download is ugly for collectors. It's also a lock. The ending is not on a disc that can walk out of a factory. It sits behind Square's servers until they open the gate. I don't know that this is why they did it. But if I was sitting in that room, trying to stop the last act of FF7 leaking a week early, I'd rather the second disc never existed.",
  paragraphs: [
    "Final Fantasy VII Revelation is coming on 8th April 2027 (yes, I'm English, so the date is the right way round). Today's topic is not the release date. It is how it ships.",
    "The game is coming on one disc. But not the full game. Square's own line is that you need an internet connection to download extra data before the physical version will play.",
    "People are in uproar. To be fair, they should be, at least about one part of this.",
    'If you sold someone a "physical game" and the box did not make it screamingly obvious that the whole game is not on that disc, that is on you. Remake had two discs. Hell, Rebirth got marketed as a two-disc release like that was a flex. Then the finale shows up with one disc and a download. You can see why that feels like a bait and switch even if the small print was there.',
    "It's easy to see why people are pissed.",
    "But since State of Play, I've been stuck on one question. What's the point of one disc versus two?",
    "That's an actual decision. They've done two discs before. Twice. Rebirth was 150GB. It wouldn't fit on a 100GB Ultra HD Blu-ray, so Square pressed two. You installed both, and after that you could leave either disc in the drive. No swapping mid-game. Either disc acted like a key. Hamaguchi said stuffing it onto one disc would have meant pulling the world back. They chose not to.",
    "Revelation faces the same problem. Looks like an even larger game. Different answer. One disc, rest of the game downloads from a server.",
    "The boring reason is money. Nobody will give you Square's invoice, so I'm not going to pretend the next bit is cold fact. Humour me. Reporting puts the whole physical chain, pressing through getting a box to a shop, at around 15 percent of a £70 sticker (about $95 as I write this). A second disc is extra cost: extra pressing, a thicker case, extra weight on a lorry.",
    "There's a self-perpetuating argument about physical sales, and it's still true. Sales dwindled. High-street stores and supermarkets piled in over a decade ago, trying to be your game shop while you picked up milk and butt soap. Traditional retailers got squeezed, cut shelf space for merch and trading cards, then closed most of the shops because they couldn't afford the lights. Then those same supermarkets decided the floor wasn't worth it, so they swapped game shelves for Prime bottles. Tesco walked. GAME's leftover presence is mostly concessions inside Sports Direct. Digital became king.",
    "At some point a publisher looks at shrinking shelf space and goes: we are not spending money to hold stock.",
    "I think that's mostly why game discs are dying. Bluntly: the less a game costs to sell, the bigger the margin. Square are not a charity.",
    "If we're being charitable, there's another reason one disc might make sense. Plastic. The west has made a meal of plastic waste and carbon for years, so a company that can score points by saying it thought about the planet, does so. Square Enix did not.",
    "A disc weighs about 20 grams. A two-disc box is heavier because of the tray. Dropping the second disc on a big print run is tonnes of plastic that never get made. And despite what the Remake-trilogy haters will say, Square are not printing a few thousand discs. They are printing millions, at least over the first few years, if Remake and Rebirth are anything to go by. I'm not turning that into a TED talk. The cost is still real.",
    'And yes, I can hear you screaming at your phone on the toilet: "a download is not free, in carbon or in money." No disc just moves the cost into data centres, your electric bill, and your internet bill if you\'re metered.',
    "A boxed copy's footprint is the object: the disc, the plastic, the press, the sleeve, the lorry. A download's footprint is electricity: a data centre sending the files, your console writing them to an SSD. Greenly, a French carbon firm, put a million boxed copies at 312 tonnes of CO2e, and a million 70GB downloads at 3 tonnes. That's how the game arrives. It's why a second disc is wasteful. So that's it, right? That's why the industry is binning discs?",
    "Not quite. Digital is not as virtuous as some claim. The same report said physical can still come out cleaner when you count the whole life of a game, from making it to playing it. Once the game is on and the TV is on, that dwarfs the disc and the box. Rough numbers: 100 hours on a PS5 and a big TV is about twenty times the CO2 of the case. So dropping disc 2 saves real waste as a product. Using that to call a download the green choice is a different argument, and a worse one, once you look at the hobby as a whole.",
    "I don't think carbon is why people are angry. Nobody pre-ordered Revelation because they wanted to save the polar bears, or those rodents that get stuck in crisp packets (chips, for my American inferiors). They wanted the game on the shelf, complete, the way Remake and Rebirth were. I get that. I wanted that too.",
    "Maybe that's why Square didn't make the green claim. So why one disc versus two?",
    "The bit I haven't seen many people say out loud is the ending.",
    "This is the last game. Everyone knows where the story is going and nobody knows how they land it. A second disc, in a game this long, is usually the back half. If that disc is in a warehouse in March, or in a reviewer's house, or in a shop that puts copies out early, someone dumps it. The last ten hours of a ten-year project end up in the sticky, blistered hands of a nerd who wants to ruin Square Enix for what they did to his beloved.",
    "A day-one download is ugly for collectors. It's also a lock. The ending is not on a disc that can walk out of a factory. It sits behind Square's servers until they open the gate. I don't know that this is why they did it. But if I was sitting in that room, trying to stop the last act of FF7 leaking a week early, I'd rather the second disc never existed.",
    "None of that makes the marketing fine.",
    "You can want the cheaper box, less plastic, the ending not sitting in cardboard in Milton Keynes. Or Detroit. You still have to tell people what they're buying.",
    'And we should be honest about what "physical" already was. After Rebirth installed, the disc was a licence check. And if your console had ever been on the internet, I\'m pretty sure you weren\'t playing without the latest update anyway.',
    'What Square should do is stop pretending they\'re down with the cool kids. A "physical edition" that won\'t play without a download is a key in a case. Call it that.',
    "Here's the part that actually bothers me. Printing one disc is worse than picking a side.",
    'They still paid to press something, sleeve it, ship it, put it on a shelf. So the cost-saving and plastic stories are half-true at best. They also still need a download, so the preservation people are right to call it a key in a box. Digital-only, said out loud — "this will not fit", "two discs are expensive", "we are not adding a skip-load of plastic for a licence check" — at least picks a side. You can fight it. Instead they didn\'t want the digital-only backlash, so they picked the cheapest way to dodge it. One disc plus a patch means Square gets hated by everyone: too digital for the shelf crowd, too physical to claim the green win.',
    'The bet was that a box in the hand would mute the "no physical" riot. It didn\'t. It just made the riot about honesty instead of format.',
    "I'm still going to play it. Probably buy the Collector's Edition too. I think this trilogy is one of the biggest things gaming has done, and I'm not dropping it because disc 2 became a patch. I just wish they'd said the quiet part first: we are not pressing two discs, here's why, and here's what you actually get in the box.",
    "If they picked one disc over two because of money, say money. If it's waste, say waste. If it's to protect the ending, say you're protecting the ending. Any of those I can live with. I think most people would too.",
    "What I cannot live with is having to defend shitty marketing to a bunch of people on X who already hate Revelation because it exists.",
  ],
} as const;
